Campaign itegration
teamco/hflow pull request #15
Opened 2022-01-09 21:35 UTC by kudenv

First Campaign Integration

2022-01-10 07:08 UTC, andrewpalkin commented
What was the reason to do changes in next file ?

src/components/Price/Rebate/Discount.js

2022-01-10 08:28 UTC, teamco reviewed
почини код

2022-01-10 08:28 UTC, teamco commented on src/models/campaign.model.js
> +            ...campaign.data(), ...{ id: campaign.id } };
старый кусок кода от файрбейса - не будет работать
посмотри сабскрипшн модель

2022-01-10 08:28 UTC, teamco commented on src/models/campaign.model.js
> +        const {price: {discount, discounted}} = payload
вытащи все данные из пэйлоада - так легче дебажить

2022-01-10 08:28 UTC, teamco commented on src/pages/campaigns/[campaign]/campaignEdit.js
> +                  helper: true,
на уровне формы отсутствуют таги

2022-01-10 12:26 UTC, kudenv commented on src/models/campaign.model.js
> +          type: setAs(payload.subscriptionType, 'Business'),
resolved

2022-01-10 12:27 UTC, kudenv commented on src/models/campaign.model.js
> +            ...campaign.data(), ...{ id: campaign.id } };
resolved

2022-01-10 12:27 UTC, kudenv commented on src/models/campaign.model.js
> +        const {price: {discount, discounted}} = payload
resolved

2022-01-10 12:27 UTC, kudenv commented on src/pages/campaigns/[campaign]/campaignEdit.js
> +    onSubscriptions,
resolved

2022-01-10 12:27 UTC, kudenv commented on src/pages/campaigns/[campaign]/campaignEdit.js
> +                  helper: true,
resolved

2022-01-12 19:27 UTC, teamco requested changes

2022-01-12 19:27 UTC, teamco commented on src/locales/en-US/translation.json
> +    "expiredAt": "Expire At",
remove startat and expiredat

2022-01-12 19:27 UTC, teamco commented on src/pages/campaigns/[campaign]/form/campaing.translate.js
> +        <div>
remove exmple section

2022-01-12 19:32 UTC, teamco reviewed
resolved

2022-01-12 19:33 UTC, merged